language: java
jdk:
  - oraclejdk8
  - openjdk8
dist: trusty

addons:
  sonarcloud:
    organization: "lecousin"
    token:
      secure: alUTUZwFaLONa+PCSXvVI4u8aw2psM8M4pjSDe+oDssdAJ3SzDrJLG7yaHoDozhALRheb6GqDILx9vsC8Ij92dmM55Wh7SAkzJiheYsvokWFc5sxAILpriekqAPeulBClIVAkSaWA6hh1DlavJTEEAunBqmXYImzM8PP3Hx5zZ36ZErz/Nekph9+M8WNQk3Jc+Rk7TLSm1fHdZ7uD2dONB9nuyZubqIMPDfajxvCpzw8oV+W/j2T/V+RQYxu2FCe0jWxHQPLJqVQzu1yCzX+p66IezgcU93T08vlTQ6NSUch5zTKApu/c/oVfHv0N4GJ21Ddn9d2oNFzzxUbsGwR/Lj0ZTlFJw0r2zfBqSTi7H/Osfz73f5BE7tXq6zdvoSLg7HRouANacQM9WWTLCjEgMszpT0L5stpn5SJ+iOqfVR0iXoI3eMWdU6D/3El1HQLFrQxNYdEf+tprjG4uuZfPBa1gmq2MPZzzIx3gGI4oGLBO1dMdgymrdA3OVcyH//2BxU7uuq5GDCbfBdf4XsBP88PpMl2eaJeoMsV+PBHInMGG3gJ62YjlYt7kUdZwC6EnqyZrh2sdAhsW8Vp+1504nq6D0nCthKRIeuYImYV6tyYnUSO4Sk7gGq7yru6xY5RcW3zXGxDn5HHf7p98pkDtfuJC3yDXfZxHAREgjqOOE4=

script: mvn test verify install sonar:sonar -Dsonar.projectKey=lecousin_java-framework-application-loader -DprojectName=java-framework-application-loader -B 
  
after_success:
 - bash <(curl -s https://codecov.io/bash)
